from .crops import CROP_SUITABILITY
from .diseases import CROP_DISEASES, DISEASE_PATTERNS
from .environmental_maps import (
    DATASET_CROP_TO_ID,
    DATASET_SOIL_TO_TEXTURE,
    TEXTURE_TO_DATASET_SOIL,
)
from .fertilizers import FERTILIZER_RECOMMENDATIONS
from .irrigation import CROP_WATER_NEEDS, SOIL_MOISTURE_THRESHOLDS

__all__ = [
    "CROP_SUITABILITY",
    "CROP_DISEASES",
    "DISEASE_PATTERNS",
    "FERTILIZER_RECOMMENDATIONS",
    "CROP_WATER_NEEDS",
    "SOIL_MOISTURE_THRESHOLDS",
    "DATASET_CROP_TO_ID",
    "DATASET_SOIL_TO_TEXTURE",
    "TEXTURE_TO_DATASET_SOIL",
]
